"""Build `dist/eigentliCH.zip` — the thing a friend with a naked laptop unzips.

    python tools/make_distribution.py

**Why a script rather than "zip the folder".** A right-click Send to > Compressed folder would put
`client/submissions/` into the archive, and those four files are real answers about named people's
finances. The repo protects them with two `.gitignore` files precisely because a copy-and-paste already
lost that protection once (30 August 2026, when they were copied out of `andersCH-prototype/`). An
archive is another copy operation and needs its own guard, not a habit.

**The guard is an assertion, not a filter.** Four layers, which must all agree. The exclusion rules
below decide what is walked. A content scan then reads every shipped text file and refuses to build if one
of them *mentions* a submitter by name — which is how personal data actually escapes, in documentation
rather than in a payload. An independent check runs immediately before every single write. A last one
re-opens the finished archive and scans its name list. A filter that silently stops matching — because a
directory was renamed, because a submission landed somewhere new — produces a ZIP that looks correct;
four layers produce a traceback instead.

Both real leaks found while writing this were caught by the layer added after them: the vault store by the
write-time listing, `PHASE-0-SURVEY.md` by the content scan. Neither was a submission and neither lived
anywhere near one.

**stdlib only, on purpose.** This is the script that packages a product whose install story is "you need
Python and nothing else". It would be a poor advertisement for that if it needed a dependency.

See DECISIONS.md A47 for what the distribution is and why it exists.
"""

from __future__ import annotations

import fnmatch
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent

#: The top-level folder inside the archive. Extracting must produce one folder, not scatter thirty files
#: into whatever directory the friend happened to be looking at.
ARCHIVE_ROOT = "eigentliCH"

OUT = PROJECT / "dist" / f"{ARCHIVE_ROOT}.zip"

#: The Modelfile lives in the sibling prototype and is referenced by INSTALL.md step 5 as a file in the
#: eigentliCH folder. It has to travel, or `ollama create -f Modelfile.apertus-8b-de` has nothing to read.
MODELFILE = PROJECT.parent / "andersCH-prototype" / "Modelfile.apertus-8b-de"

#: `dist/` holds the manual, the prompt and the setup script, and they belong at the archive's ROOT where
#: someone who has just extracted it will see them. The folder itself is not shipped: it would nest the
#: manual one level below the thing it documents, and it is also where this script writes its own output.
DIST_TO_ROOT = ("README.md", "INSTALL.md", "CLAUDE.md", "setup.cmd")

#: Directories never walked. Build output, caches and environments — everything here is reproducible from
#: what does ship, and `.venv` alone is tens of thousands of files.
PRUNED_DIRS = frozenset(
    {".venv", "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache", ".git", "node_modules",
     "dist"}
)

#: Files excluded by name. The database is member data (K2, and K3 from phase 3) and is regenerated by
#: `alembic upgrade head` during setup, so shipping it would be both a disclosure and a downgrade.
EXCLUDED_FILE_PATTERNS = (
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "eigentlich.db",
    "eigentlich.db-journal",
    "eigentlich.db-wal",
    "eigentlich.db-shm",
    "*.sqlite",
    "*.sqlite3",
    ".env",
    "*.zip",
    "Thumbs.db",
    ".DS_Store",
)

#: **The personal-data rules.** Kept separate from the ordinary exclusions above because these are the
#: ones the assertion enforces: an ordinary exclusion slipping through ships a stale cache file, one of
#: these slipping through discloses a named person's finances.
#:
#: Each tree is excluded whole rather than by filename, because the protection must survive someone
#: adding a `.csv`, a `.txt` or a subfolder to it. The list is `.gitignore`'s personal-data half, restated
#: — the two must be read together, and anything added there belongs here on the same day.
#:
#: `backend/vault_store/` earned its place the hard way: the first run of this script listed two vault
#: blobs among the files it was about to ship, because the rules named submissions and the database and
#: stopped there. The vault is K3 — the documents a member uploaded — and it lives outside the database
#: precisely so those bytes are not carried by every incidental copy. A ZIP is an incidental copy.
#:
#: `exports/` is R-154's output: a full member export is the most concentrated K3 artefact the system can
#: produce. It is listed here rather than pruned as build output, so that finding one is reported as a
#: policy exclusion and not as a swept-up cache.
PERSONAL_DATA_DIRS = (
    ("client/submissions", "real onboarding submissions about named people"),
    ("backend/vault_store", "K3 — the document bytes a member uploaded"),
    ("vault_store", "K3 — the document bytes a member uploaded"),
    ("exports", "R-154 member exports"),
)

#: Filename patterns that mark a submission wherever it has been copied to. Two shapes, matching the repo
#: root's own `.gitignore`:
#:
#: - `*-onboarding-*.json` catches `eigentlich-onboarding-<SomeName>.json` and anything downloaded as
#:   `eigentlich-onboarding-2026-08-05.json`. It deliberately does NOT match `onboarding-questions.json`,
#:   which is product content and has to ship.
#: - `*onboarding-*.json` is the broader net and is applied ONLY under a submissions directory, where
#:   everything is personal by definition. Applied globally it would exclude the question catalogue.
PERSONAL_DATA_PATTERNS_ANYWHERE = ("*-onboarding-*.json", "*-export-*.json", "*-export-*.zip")
PERSONAL_DATA_PATTERNS_IN_SUBMISSIONS = ("*onboarding-*.json",)

#: Files that are clean as paths and not clean as text.
#:
#: `PHASE-0-SURVEY.md` §2 tabulates the submissions **by filename**, and those filenames are real people's
#: names. No financial answer is quoted, but the table still says that three named people are eigentliCH
#: members and how many questions each answered — and membership is itself a personal fact. It is an
#: internal survey with no install value, so it does not travel. Left untouched in the repo, where it
#: belongs and where it is already gitignore-adjacent rather than distributed.
#:
#: This entry is a decision, not a rule, and the content scan below is what finds the next one.
EXCLUDED_DOCUMENTS = {
    "PHASE-0-SURVEY.md": "names real submitters in its §2 table of submission filenames",
}

#: Text formats worth scanning for names. A `.ico` cannot contain a legible surname and a scan of one is
#: noise; every format here is something a person writes prose into.
SCANNED_SUFFIXES = frozenset({".md", ".py", ".js", ".json", ".html", ".css", ".txt", ".cmd", ".ps1",
                              ".toml", ".ini", ".mako", ""})


class DistributionPolicyError(AssertionError):
    """A path the distribution must never carry reached the point of being written."""


def _posix(path: Path) -> str:
    return path.relative_to(PROJECT).as_posix()


def personal_data_reason(relative: str) -> str | None:
    """Why `relative` must never be distributed, or None.

    Takes a project-relative POSIX string rather than a Path so that the same function can be run against
    the finished archive's name list, where there are no Paths at all.
    """
    parts = relative.split("/")
    name = parts[-1]

    for folder, note in PERSONAL_DATA_DIRS:
        if relative == folder or relative.startswith(f"{folder}/"):
            return f"under {folder}/ — {note}"
        # A bare name matches at any depth. `vault_store` is configured as a path under `backend/` today,
        # but where the store is rooted is a configuration line in `api/main.py` — the exclusion must not
        # depend on it staying where it is.
        if "/" not in folder and folder in parts[:-1]:
            return f"inside a {folder}/ directory — {note}"

    if "submissions" in parts[:-1]:
        for pattern in PERSONAL_DATA_PATTERNS_IN_SUBMISSIONS:
            if fnmatch.fnmatch(name, pattern):
                return f"matches {pattern} inside a submissions directory"

    for pattern in PERSONAL_DATA_PATTERNS_ANYWHERE:
        if fnmatch.fnmatch(name, pattern):
            return f"matches {pattern} — a saved onboarding submission"

    if name.startswith("eigentlich.db"):
        return "the application database — member plan and vault data"

    return None


def _excluded_reason(relative: str) -> str | None:
    """Every reason a file is left out, personal-data rules first."""
    reason = personal_data_reason(relative)
    if reason is not None:
        return reason
    name = relative.rsplit("/", 1)[-1]
    if relative in EXCLUDED_DOCUMENTS:
        return EXCLUDED_DOCUMENTS[relative]
    for pattern in EXCLUDED_FILE_PATTERNS:
        if fnmatch.fnmatch(name, pattern):
            return f"matches {pattern}"
    return None


def submitter_tokens() -> set[str]:
    """Names to scan the shipped text for, read off the submission filenames themselves.

    **Derived, never written down here.** Hardcoding "do not ship these three surnames" would put three
    real surnames into a file that is itself distributed — the mistake it exists to prevent — and would go
    stale the moment a fourth submission arrives. Reading the directory means the guard tracks reality and
    the source stays clean.

    `eigentlich-onboarding-<Name>.json` yields `<Name>`. Dated downloads yield `2026` and `08`, which the
    alphabetic-and-long-enough filter drops: a scan for `08` matches everything, and a guard that always
    fires teaches people to switch it off.

    The placeholder in the line above is a placeholder for a reason. An earlier draft of this docstring
    used a real filename as its example, and the scan refused to build the distribution because of it —
    correctly, and while it was being written. Worth leaving on the record.
    """
    tokens: set[str] = set()
    root = PROJECT / "client" / "submissions"
    if not root.exists():
        return tokens
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        for piece in path.stem.replace("_", "-").split("-"):
            piece = piece.strip("() ")
            if len(piece) >= 5 and piece.isalpha() and piece.lower() not in {"eigentlich", "onboarding"}:
                tokens.add(piece)
    return tokens


def _scan_for_names(included: list[tuple[Path, str]], tokens: set[str]) -> list[tuple[str, str]]:
    """Shipped files whose TEXT carries a submitter's name, however clean their path looks.

    The path rules cannot see this. `PHASE-0-SURVEY.md` is not a submission and does not live near one; it
    simply talks about them by name, which is how personal data usually escapes — not smuggled in the
    payload, mentioned in the documentation.
    """
    found: list[tuple[str, str]] = []
    if not tokens:
        return found
    for source, arcname in included:
        if source.suffix.lower() not in SCANNED_SUFFIXES:
            continue
        text = source.read_bytes().decode("utf-8", errors="ignore")
        hits = sorted(token for token in tokens if token in text)
        if hits:
            found.append((arcname, ", ".join(hits)))
    return found


def _collect() -> tuple[list[tuple[Path, str]], list[tuple[str, str]], list[str]]:
    """(what ships, what was excluded and why, which directories were pruned unwalked)."""
    included: list[tuple[Path, str]] = []
    excluded: list[tuple[str, str]] = []
    pruned: list[str] = []

    def walk(folder: Path) -> None:
        for entry in sorted(folder.iterdir(), key=lambda p: (p.is_file(), p.name.lower())):
            relative = _posix(entry)
            if entry.is_dir():
                # A pruned directory is reported and not descended into. `client/submissions/` is the one
                # exception: it is walked so that every excluded file is named in the output, because
                # "excluded 4 files" is not a claim anyone can check.
                if personal_data_reason(relative) is not None:
                    for inner in sorted(entry.rglob("*")):
                        if inner.is_file():
                            excluded.append((_posix(inner), personal_data_reason(_posix(inner)) or "policy"))
                    continue
                if entry.name in PRUNED_DIRS:
                    pruned.append(f"{relative}/")
                    continue
                walk(entry)
                continue
            reason = _excluded_reason(relative)
            if reason is not None:
                excluded.append((relative, reason))
                continue
            included.append((entry, f"{ARCHIVE_ROOT}/{relative}"))

    walk(PROJECT)
    return included, excluded, pruned


def _extras() -> list[tuple[Path, str]]:
    """Files that ship from somewhere other than where they live in the source tree."""
    extras: list[tuple[Path, str]] = []
    for name in DIST_TO_ROOT:
        source = PROJECT / "dist" / name
        if not source.exists():
            raise SystemExit(f"missing: {source}\nthe distribution is not shippable without it")
        extras.append((source, f"{ARCHIVE_ROOT}/{name}"))

    if not MODELFILE.exists():
        raise SystemExit(
            f"missing: {MODELFILE}\n"
            "INSTALL.md step 5 tells the reader to run `ollama create apertus:8b -f Modelfile.apertus-8b-de`\n"
            "in the folder they extracted. Shipping without it makes that instruction impossible to follow."
        )
    extras.append((MODELFILE, f"{ARCHIVE_ROOT}/{MODELFILE.name}"))
    return extras


def _assert_shippable(arcname: str) -> None:
    """The independent check, run on every write and again on the finished archive."""
    relative = arcname[len(ARCHIVE_ROOT) + 1 :] if arcname.startswith(f"{ARCHIVE_ROOT}/") else arcname
    reason = personal_data_reason(relative)
    if reason is not None:
        raise DistributionPolicyError(
            f"REFUSING TO WRITE {arcname}: {reason}.\n"
            "This is the guard in A47 firing. The collection rules and the write-time check disagree, "
            "which means one of them is wrong — fix the rule, do not remove the check."
        )


def main() -> int:
    included, excluded, pruned = _collect()
    included = sorted(included + _extras(), key=lambda pair: pair[1])

    # Before anything is written. A ZIP that has to be deleted again is a ZIP that existed, and on a
    # laptop that is backed up, briefly existing is enough.
    tokens = submitter_tokens()
    leaks = _scan_for_names(included, tokens)
    if leaks:
        report = "\n".join(f"    {arcname}  mentions: {hits}" for arcname, hits in leaks)
        raise DistributionPolicyError(
            "REFUSING TO BUILD. These files ship, and their text names real submitters:\n"
            f"{report}\n\n"
            "The path rules cannot catch this — the files are not submissions, they talk about them.\n"
            "Either add the file to EXCLUDED_DOCUMENTS with a reason, or change the file so it does not\n"
            "name anybody. Do not add the name to an allowlist."
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for source, arcname in included:
            _assert_shippable(arcname)
            archive.write(source, arcname)

    # Third layer: read back what was actually written. The two checks above reason about what the code
    # intended to do; this one reasons about the file that now exists on disk.
    with zipfile.ZipFile(OUT) as archive:
        names = archive.namelist()
        for name in names:
            _assert_shippable(name)

    print(f"\n  {OUT}")
    print(f"  {len(names)} files, {OUT.stat().st_size / 1_048_576:.2f} MB\n")

    print("  INCLUDED")
    for _, arcname in included:
        print(f"    {arcname}")

    print("\n  EXCLUDED — by policy, these are the ones that matter")
    personal = [
        (rel, why) for rel, why in excluded
        if personal_data_reason(rel) is not None or rel in EXCLUDED_DOCUMENTS
    ]
    for rel, why in sorted(personal):
        print(f"    {rel}\n      {why}")
    if not personal:
        # Not reassuring: it means the submissions are gone, or the rule stopped matching them.
        print("    none found — check that client/submissions/ still exists and is still protected")

    other = [
        (rel, why) for rel, why in excluded
        if personal_data_reason(rel) is None and rel not in EXCLUDED_DOCUMENTS
    ]
    if other:
        print("\n  EXCLUDED — build output and caches")
        for rel, why in sorted(other):
            print(f"    {rel}  ({why})")

    if pruned:
        print("\n  NOT WALKED")
        for folder in sorted(pruned):
            print(f"    {folder}")

    print(f"\n  {len(names)} archive paths re-checked after writing; no submission, no vault blob and no")
    print(f"  database among them. {len(included)} shipped files were scanned for {len(tokens)} submitter")
    print("  names taken off the submission filenames, and none appears in the text.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
