"""position liquidity band, for R-031

Revision ID: 13d2a5ebfe32
Revises: 37513e444298
Create Date: 2026-08-30 17:41:56.041118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d2a5ebfe32'
down_revision: Union[str, Sequence[str], None] = '37513e444298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquidity', sa.Enum('immediate', 'within_months', 'within_years', 'illiquid', name='liquidity'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('liquidity')

    # ### end Alembic commands ###
