"""member_facts and decision_facts: the five instrument keys

Revision ID: 42975d339a0b
Revises: d5b71fc02e83
Create Date: 2026-09-04

A127. `member_facts` holds the five keys the owner named on 4 September 2026 — canton, civil status,
health, network size and education — and `decision_facts` links them to the Decision that recorded them,
which C-09 requires rather than merely prefers: `Decision.covered_plan_objects` is what the guard compares
against, so a `PlanMutable` row with no link table cannot be written at all.

**Written by hand, and that is worth recording.** `alembic revision --autogenerate` produced three edits
that belong to nothing in this change:

  * `create_table('decision_households')` and `create_table('decision_household_members')` — both already
    created by `a3f1e90c7b45`.
  * `drop_constraint('ck_households_stated_by')` — a real constraint on a real table, which this migration
    would have removed from every database that ran it.

All three are artefacts of comparing the model against a development database that was behind head, not
findings about the schema. The third is the dangerous one and it is the kind autogenerate produces
silently: a migration whose *stated* purpose is to add two tables, quietly weakening a third. It is also
the same failure mode as the trigger defect recorded in `DECISIONS.md` — a migration doing something other
than what its name says, in a place nobody re-reads.

The autogenerated body also referenced `eigentlich.models.base.DateTime` without importing it, so the file
as generated would not have run.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from eigentlich.models.base import DateTime

# revision identifiers, used by Alembic.
revision: str = "42975d339a0b"
down_revision: Union[str, Sequence[str], None] = "d5b71fc02e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "member_facts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("member_id", sa.String(length=32), nullable=False),
        sa.Column("stated_key", sa.String(length=64), nullable=False),
        sa.Column("stated_value", sa.JSON(), nullable=False),
        sa.Column("stated_on", sa.Date(), nullable=False),
        sa.Column("stated_by", sa.String(length=16), nullable=False),
        sa.Column("superseded_on", sa.Date(), nullable=True),
        sa.Column("data_class", sa.Integer(), nullable=False),
        sa.Column("created_at", DateTime(timezone=True), nullable=False),
        # Spelled out rather than taken from `STATED_BY`, because a migration is a historical record: it
        # has to keep meaning what it meant if that tuple ever gains a third initiator.
        sa.CheckConstraint(
            "stated_by IN ('member', 'curator')", name="ck_member_facts_stated_by"
        ),
        sa.CheckConstraint(
            "superseded_on IS NULL OR superseded_on >= stated_on",
            name="ck_member_facts_superseded_after_stated",
        ),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("member_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_facts_member_id"), ["member_id"], unique=False
        )
        # Partial: the superseded rows are the history, and there may be many of them per key. Without
        # the predicate this would refuse a member's second canton outright.
        batch_op.create_index(
            "uq_member_facts_one_current",
            ["member_id", "stated_key"],
            unique=True,
            sqlite_where=sa.text("superseded_on IS NULL"),
        )

    op.create_table(
        "decision_facts",
        sa.Column("decision_id", sa.String(length=32), nullable=False),
        sa.Column("member_fact_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"]),
        sa.ForeignKeyConstraint(["member_fact_id"], ["member_facts.id"]),
        sa.PrimaryKeyConstraint("decision_id", "member_fact_id"),
    )


def downgrade() -> None:
    op.drop_table("decision_facts")
    with op.batch_alter_table("member_facts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_member_facts_one_current", sqlite_where=sa.text("superseded_on IS NULL")
        )
        batch_op.drop_index(batch_op.f("ix_member_facts_member_id"))
    op.drop_table("member_facts")
