"""member: onboarding_completed_at, so completion cannot run twice

Revision ID: 79c7db8e0c69
Revises: d9a4ab2b147c
Create Date: 2026-08-30 16:55:53.561944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c7db8e0c69'
down_revision: Union[str, Sequence[str], None] = 'd9a4ab2b147c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed_at')

    # ### end Alembic commands ###
