"""submissions: the intake file kept verbatim

**Hand-edited, and the edit matters.** Autogenerate also emitted a DROP of `ck_households_stated_by`, a
real CHECK constraint on a real table that nothing in this change touches. It is the same false positive
this project has seen before: SQLite reflects a named CHECK in a way the comparison does not recognise, so
every autogenerated revision proposes to remove it. Applying that would silently widen `households.stated_by`
to accept any string. Both directions of it are removed here; only the new table remains.

Revision ID: aef04e0d683b
Revises: b7c2f1e48a30
Create Date: 2026-09-06 02:44:28.310102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import eigentlich.models.base


# revision identifiers, used by Alembic.
revision: str = 'aef04e0d683b'
down_revision: Union[str, Sequence[str], None] = 'b7c2f1e48a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('collected_on', sa.String(length=10), nullable=True),
    sa.Column('received_at', eigentlich.models.base.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('household_code', sa.String(length=80), nullable=True),
    sa.Column('mapping_report', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', eigentlich.models.base.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_household_code'), ['household_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_member_id'), ['member_id'], unique=False)
        batch_op.create_index('uq_submission_member_hash', ['member_id', 'content_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('uq_submission_member_hash')
        batch_op.drop_index(batch_op.f('ix_submissions_member_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_household_code'))

    op.drop_table('submissions')
    # ### end Alembic commands ###
