"""spine

Revision ID: bd3fedd3d5cb
Revises: 
Create Date: 2026-08-30 15:30:57.410463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3fedd3d5cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumption_sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.Column('horizons', sa.JSON(), nullable=False),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_assumption_sets_version')
    )
    with op.batch_alter_table('assumption_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assumption_sets_effective_from'), ['effective_from'], unique=False)

    op.create_table('capabilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rung', sa.String(length=60), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_units',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_ref', sa.String(length=300), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('capability_ids', sa.JSON(), nullable=False),
    sa.Column('ip_owner', sa.String(length=120), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('age_at_registration', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('stage_hint', sa.String(length=32), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age_at_registration >= 25', name='ck_members_age_floor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_assertions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('capability_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_kind', sa.String(length=60), nullable=False),
    sa.Column('evidence_ref', sa.String(length=300), nullable=True),
    sa.Column('assessed_by', sa.String(length=120), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capability_assertions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_assertions_capability_id'), ['capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_assertions_member_id'), ['member_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('document_version', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_member_id'), ['member_id'], unique=False)

    op.create_table('curator_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('curator_id', sa.String(length=120), nullable=False),
    sa.Column('opened_from', sa.String(length=120), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('liability_flag', sa.Boolean(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curator_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curator_sessions_member_id'), ['member_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('safety', sa.String(length=40), nullable=True),
    sa.Column('liquidity_need', sa.String(length=40), nullable=True),
    sa.Column('volatility_tolerance', sa.String(length=40), nullable=True),
    sa.Column('horizon', sa.String(length=40), nullable=True),
    sa.Column('flexibility', sa.String(length=40), nullable=True),
    sa.Column('template', sa.String(length=40), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_member_id'), ['member_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('growth', 'income', 'stabilisation', 'protection', name='role'), nullable=False),
    sa.Column('capital_type', sa.Enum('human', 'financial', name='capital_type'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('magnitude_unit', sa.Enum('chf_per_year', 'share_of_total', name='magnitude_unit'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('time_basis', sa.String(length=80), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(magnitude IS NULL) = (magnitude_unit IS NULL)', name='ck_positions_magnitude_has_unit'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_member_id'), ['member_id'], unique=False)

    op.create_table('vault_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('policy', 'statement', 'contract', 'note', 'arrangement', 'learning', 'other', name='vault_kind'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.Enum('upload', 'forward', 'import', 'capture', 'manual', name='vault_source'), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['vault_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_items_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_items_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_items_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('trigger_kind', sa.String(length=60), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acted', 'dismissed', 'expired', name='action_status'), nullable=False),
    sa.Column('prepared_options', sa.JSON(), nullable=False),
    sa.Column('source_vault_item_id', sa.String(length=32), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('json_array_length(prepared_options) >= 2', name='ck_action_items_prepared_options_min'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['source_vault_item_id'], ['vault_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_source_vault_item_id'), ['source_vault_item_id'], unique=False)

    op.create_table('curator_session_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('opened', 'granted', 'revoked', 'note', 'closed', name='curator_event_kind'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['curator_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curator_session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curator_session_events_session_id'), ['session_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('author', sa.Enum('member', 'curator', 'system', name='decision_author'), nullable=False),
    sa.Column('author_ref', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_considered', sa.JSON(), nullable=False),
    sa.Column('choice', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('curator_session_id', sa.String(length=32), nullable=True),
    sa.Column('corrects_id', sa.String(length=32), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrects_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['curator_session_id'], ['curator_sessions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_corrects_id'), ['corrects_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_curator_session_id'), ['curator_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_member_id'), ['member_id'], unique=False)

    op.create_table('goal_funding',
    sa.Column('goal_id', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'position_id')
    )
    op.create_table('decision_goals',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('goal_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'goal_id')
    )
    op.create_table('decision_positions',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'position_id')
    )
    op.create_table('decision_vault_items',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('vault_item_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['vault_item_id'], ['vault_items.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'vault_item_id')
    )
    # ### end Alembic commands ###

    # R-040 and C-10: append-only, enforced by the store rather than by callers.
    #
    # These are not in `Base.metadata`, so autogenerate cannot see them and a future `--autogenerate` will
    # not notice if they go missing. They are re-asserted here because a trigger that exists only in
    # `db.create_all` would be present in tests and absent from every real database — which is the one
    # place the guarantee has to hold.
    for table, reason in (
        ("decisions", "R-040 - a correction is a new record referencing the prior one"),
        ("curator_session_events", "C-10 - immutable append-only audit table"),
    ):
        for verb in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER IF NOT EXISTS trg_{table}_no_{verb.lower()} "
                f"BEFORE {verb} ON {table} BEGIN "
                f"SELECT RAISE(ABORT, '{table} is append-only: {reason}'); "
                f"END;"
            )



def downgrade() -> None:

    for table in ("decisions", "curator_session_events"):
        for verb in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_no_{verb};")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_vault_items')
    op.drop_table('decision_positions')
    op.drop_table('decision_goals')
    op.drop_table('goal_funding')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_member_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_curator_session_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_corrects_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('curator_session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curator_session_events_session_id'))

    op.drop_table('curator_session_events')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_source_vault_item_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_member_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_items_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_vault_items_member_id'))
        batch_op.drop_index(batch_op.f('ix_vault_items_expiry_date'))

    op.drop_table('vault_items')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_member_id'))

    op.drop_table('positions')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_member_id'))

    op.drop_table('goals')
    with op.batch_alter_table('curator_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curator_sessions_member_id'))

    op.drop_table('curator_sessions')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_member_id'))

    op.drop_table('consents')
    with op.batch_alter_table('capability_assertions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_assertions_member_id'))
        batch_op.drop_index(batch_op.f('ix_capability_assertions_capability_id'))

    op.drop_table('capability_assertions')
    op.drop_table('members')
    op.drop_table('learning_units')
    op.drop_table('capabilities')
    with op.batch_alter_table('assumption_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assumption_sets_effective_from'))

    op.drop_table('assumption_sets')
    # ### end Alembic commands ###
