"""curators, access grants, marketplace and gatherings (phases 5, 7, 8)

Revision ID: c23a32d04b12
Revises: 28fc468464dc
Create Date: 2026-08-30 18:11:14.017683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23a32d04b12'
down_revision: Union[str, Sequence[str], None] = '28fc468464dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_label', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fictional', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.Column('password_salt', sa.LargeBinary(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gatherings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('lecture', 'cafe_evening', 'meetup', name='gathering_kind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('fictional', sa.Boolean(), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gatherings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gatherings_held_on'), ['held_on'], unique=False)

    op.create_table('attendances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('gathering_id', sa.String(length=32), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gathering_id'], ['gatherings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_gathering_id'), ['gathering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_member_id'), ['member_id'], unique=False)

    op.create_table('member_offers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('offer', 'search', name='offer_direction'), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fictional', sa.Boolean(), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_offers_member_id'), ['member_id'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=320), nullable=True),
    sa.Column('member_id', sa.String(length=32), nullable=True),
    sa.Column('fictional', sa.Boolean(), nullable=False),
    sa.Column('billing_plan', sa.String(length=40), nullable=True),
    sa.Column('billing_fee_chf', sa.Float(), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_member_id'), ['member_id'], unique=False)

    op.create_table('access_grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('curator_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('curator_session_id', sa.String(length=32), nullable=True),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curator_id'], ['curators.id'], ),
    sa.ForeignKeyConstraint(['curator_session_id'], ['curator_sessions.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grants_curator_id'), ['curator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_curator_session_id'), ['curator_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_member_id'), ['member_id'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('domain', sa.Enum('financial', 'health', 'education', name='listing_domain'), nullable=False),
    sa.Column('qualification_pipeline', sa.Enum('capability', 'professional_registration', name='qualification_pipeline'), nullable=False),
    sa.Column('registration_refs', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'withdrawn', name='listing_status'), nullable=False),
    sa.Column('standing_inputs', sa.JSON(), nullable=False),
    sa.Column('fictional', sa.Boolean(), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(domain = 'financial' AND qualification_pipeline = 'capability') OR (domain IN ('health', 'education') AND qualification_pipeline = 'professional_registration')", name='ck_listings_pipeline_matches_domain'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_provider_id'), ['provider_id'], unique=False)

    op.create_table('disclosures',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('listing_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('declared_by', sa.String(length=120), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosures_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosures_listing_id'))

    op.drop_table('disclosures')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_provider_id'))

    op.drop_table('listings')
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grants_member_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_curator_session_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_curator_id'))

    op.drop_table('access_grants')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_member_id'))

    op.drop_table('providers')
    with op.batch_alter_table('member_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_offers_member_id'))

    op.drop_table('member_offers')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_member_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_gathering_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('gatherings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gatherings_held_on'))

    op.drop_table('gatherings')
    op.drop_table('curators')
    # ### end Alembic commands ###
