"""onboarding answers: one row per question (R-101)

Revision ID: d9a4ab2b147c
Revises: bd3fedd3d5cb
Create Date: 2026-08-30 16:49:55.196351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a4ab2b147c'
down_revision: Union[str, Sequence[str], None] = 'bd3fedd3d5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('question_key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question_set_version', sa.String(length=40), nullable=False),
    sa.Column('data_class', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'question_key', name='uq_onboarding_answer')
    )
    with op.batch_alter_table('onboarding_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_answers_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_answers_member_id'))

    op.drop_table('onboarding_answers')
    # ### end Alembic commands ###
