"""curator must_change

Revision ID: ed7a417e4348
Revises: ee959786d912
Create Date: 2026-08-30 18:54:53.192386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7a417e4348'
down_revision: Union[str, Sequence[str], None] = 'ee959786d912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite cannot ADD a NOT NULL column without a default: the existing rows need a value at the moment
    # the column appears. `0` is right for them — a curator created before this column existed was never
    # asked to change anything.
    with op.batch_alter_table('curators', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('must_change', sa.Boolean(), nullable=False, server_default=sa.text('0'))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curators', schema=None) as batch_op:
        batch_op.drop_column('must_change')

    # ### end Alembic commands ###
