"""member_id nullable on the append-only rows, for R-231 erasure

Revision ID: ee959786d912
Revises: c23a32d04b12
Create Date: 2026-08-30 18:51:22.609940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee959786d912'
down_revision: Union[str, Sequence[str], None] = 'c23a32d04b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# **`batch_alter_table` RECREATES the table, and a recreated table has no triggers.**
#
# SQLite cannot alter a column in place, so batch mode copies the rows into a new table and renames it.
# Everything attached to the old table goes with it — including `trg_decisions_no_update` and
# `trg_decisions_no_delete`, which are how R-040 is enforced against raw SQL.
#
# This migration silently switched them off. The ORM guard in `db.py` still held, so nothing failed and no
# test noticed; only a trigger count on a migrated database showed it. Both directions re-install them,
# and `test_every_append_only_trigger_survives_a_migration` now fails if a future migration does the same.
from sqlalchemy import text  # noqa: E402

from eigentlich.db import append_only_trigger_statements  # noqa: E402


def _restore_triggers() -> None:
    """Re-create them on the migration's OWN connection.

    This used to call `install_append_only_triggers(op.get_bind().engine)`, and `.engine` opens a *second*
    connection outside the migration's transaction. That connection still saw the pre-swap `decisions`
    table, whose triggers were still attached, so `CREATE TRIGGER IF NOT EXISTS` did nothing at all. The
    batch swap then committed and took the real triggers with it. A migrated database ended up with zero
    `decisions` triggers while `create_all` — which every test and the development database use — installed
    them correctly, so nothing anywhere went red.

    That is the same second-connection mistake as the R-231 erasure bug, in a different file, which is why
    `append_only_trigger_statements()` exists and why this must not reach for an Engine.
    """
    bind = op.get_bind()
    for statement in append_only_trigger_statements():
        bind.execute(text(statement))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curator_sessions', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###

    _restore_triggers()

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    with op.batch_alter_table('curator_sessions', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###

    _restore_triggers()
